server:
  port: 8083

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  datasource:
    url: jdbc:mysql://${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      s3:
        bucket: couponmoa-coupon-prod
  application:
    name: couponmoa
  google:
    api:
      key: ${GOOGLE_API_KEY}


grpc:
  client:
    user-service:
      address: static://couponmoa-dev-user-service.couponmoa.local:6565
      negotiation-type: plaintext
    store-service:
      address: static://couponmoa-dev-store-service.couponmoa.local:6565
      negotiation-type: plaintext
  server:
    port: 6565