server:
  port: 8083

spring:
  application:
    name: couponmoa
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  datasource:
    url: jdbc:mysql://${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      time-to-live: 900000

  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      s3:
        bucket: couponmoa-coupon-prod

grpc:
  client:
    user-service:
      address: static://couponmoa-dev-user-service.couponmoa.local:6565
      negotiation-type: plaintext
    store-service:
      address: static://couponmoa-dev-store-service.couponmoa.local:6565
      negotiation-type: plaintext
  server:
    port: 6565


management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 9090

app:
  store:
    alert-url: http://couponmoa-dev-store-service.couponmoa.local:8082/api/v1/stores/{storeId}/alert

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure: DEBUG
    com.fasterxml.jackson: DEBUG
    com.couponmoa.backend.couponmoacoupon.config.JacksonConfig: DEBUG