name: Deploy to ECS

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ap-northeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SPRING_PROFILE: prod
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  RDS_URL: ${{ secrets.RDS_URL }}
  RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
#  ELASTIC_SEARCH_URL: ${{ ELASTIC_SEARCH_URL }}
#  GOOGLE_API_KEY: ${{ GOOGLE_API_KEY }}

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with proto generation
        run: ./gradlew generateProto build -x asciidoctor

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Debug Secret Values
        run: |
          echo "AWS_ACCOUNT_ID Secret: ${{ secrets.AWS_ACCOUNT_ID }}"
          echo "ECR_REPOSITORY Secret: ${{ secrets.ECR_REPOSITORY }}"
          echo "AWS_REGION Env: ${{ env.AWS_REGION }}"
        shell: bash
      
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check if coupon directory exists
        run: |
          if [ ! -d "./coupon" ]; then
            echo "Coupon directory does not exist"
            exit 1
          fi

      - name: Build Docker image
        id: build_image
        shell: bash
        run: |                  
          IMAGE_TAG=${{ github.sha }}
          
          AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"
          ECR_REPO="${{ secrets.ECR_REPOSITORY }}"
          REGION="${{ env.AWS_REGION }}"
          
          FULL_IMAGE_TAG="${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
          
          echo "Attempting to build image with tag: ${FULL_IMAGE_TAG}"
          
          docker build -t "${FULL_IMAGE_TAG}" -f ./Dockerfile ./coupon 
          
          echo "built_image_tag=${FULL_IMAGE_TAG}" >> "$GITHUB_OUTPUT"

      - name: Push to ECR
        shell: bash
        run: |
          docker push ${{ steps.build_image.outputs.built_image_tag }}
          
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_FAMILY }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: couponmoa-dev-coupon-container
          image: ${{ steps.build_image.outputs.built_image_tag }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_NAME }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
